logging:
  level:
    ROOT: INFO

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3355/school?useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog/master.xml
    enabled: true

server:
  port: 9022
